on: [push]

jobs:
  ubuntu_var_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: printdefualtvariablesubuntu
        shell: pwsh 
        run: throw 'some error'
      
      
      - name: runifsuccess
        if: ${{ success() }}
        run: echo 'run on prev steps success'
        
      - name: runiferror
        if: ${{ failure() }}
        run: echo 'run because faild step'
        
      - name: runifsuccess
        if: ${{ always() }}
        run: echo 'run always'
      
