on: [push]

jobs:
  ubuntu_var_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: printdefualtvariablesubuntu 
        run: echo ${GITHUB_RUN_ID}
                  ${GITHUB_RUN_NUMBER}
